### ISSUE TITLE
Trying to load external css

### ISSUE THREAD

**Issue by amboy00** [addyosmani/grunt-uncss#161]
When I run ```grunt build``` I get the following error:

```bash
Running "uncss:dist" (uncss) task
Fatal error: uncss/node_modules/css: unable to parse http://use.typekit.net/c/8e186a/1w;aw-conqueror-carved-four,2,XzC:P:n4;aw-conqueror-carved-one,2,Xz8:P:n4;ff-tisa-web-pro,2,Vdl:P:i4,Vdk:P:n4,Vdp:P:n7/k?3bb2a6e53c9684ffdc9a9bf71f5b2a623df248a4a1ae63c3259906d27e337db8088990e037ff15fa5219533470fc94a4fb850d98f7454d4a1b61526f720ce022c5d27e978632b20c719ca4fbca254b2394a3a66362c622cb9920f77239a24b167d3e03eb454e0214e2e78d6486aa3de5f4b45b :
missing '{' near line 13:1
	8:        	</head>
	9:        	<body>
	10:        		<h1>403 - Forbidden</h1>
	11:        	</body>
	12:        </html>
	13:     -> 
```

So I guess this is coming from the CSS module?  It looks like it's trying to parse a typkit css file that's called via javascript.

In my gruntfile, I think I'm pointing at just the css file.

```javascript
    uncss: {
      dist: {
        options: {
          htmlroot : '<%= config.app %>'
        },
        files: {
          'styles/core.css': ['<%= config.app %>/index.html', '<%= config.app %>/other.html']
        }
      }
    }
```

The only place Typekit gets called is in a script call.  I suppose I could point to an actual css file in my proxy to get around it, but I'd rather this compile without that extra step.

Any ideas what's going on?

**Comment by XhmikosR** [comment]
Try with uncss itself; this sounds like an upstream issue.

**Comment by amboy00** [comment]
This is part of the grunt build process, so I commented out all the other steps.  I still get the error.  So I went back to a previous version – 0.3.5 – and ran it again.  This time it worked without error!  Then I went from the latest tag version and worked back until it worked and the latest version to work without error is 0.3.8.

I'm not sure what the difference would be in this case.

**Comment by XhmikosR** [comment]
That is why I told you to try with uncss itself. In v0.3.8 we updated uncss.

**Comment by amboy00** [comment]
Sure thing. I assumes you meant just with grunt since it a grunt package.  How do I run it by itself?

**Comment by XhmikosR** [comment]
https://github.com/giakki/uncss#from-the-command-line

And try to replicate your config. My guess is it will fail too. Also, make sure you use `/foo/bar.js` and not `foo/bar.js` since uncss has problems with that.

**Comment by amboy00** [comment]
When I use the shell script to run this, I still get the error I got before, but with a bit more information.  I did run into that problem of making the initial CSS file relative and not absolute like you mentioned.

```bash
$ ./node_modules/grunt-uncss/node_modules/uncss/bin/uncss app/index.html dest/styles/main.css

/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:36
        fn = function () { throw arg; };
                                 ^
Error: uncss/node_modules/css: unable to parse http://use.typekit.net/c/8e186a/1w;aw-conqueror-carved-four,2,XzC:P:n4;aw-conqueror-carved-one,2,Xz8:P:n4;ff-tisa-web-pro,2,Vdl:P:i4,Vdk:P:n4,Vdp:P:n7/k?3bb2a6e53c9684ffdc9a9bf71f5b2a623df248a4a1ae63c3259906d27e337db8088990e037ff15fa5219533470fc94a4fb850d98f7454d4a1b61526f720ce022c5d27e978632b20c719ca4fbca254b2394a3a66362c622cb9920f77239a24b167d3e03eb454e0214e2e78d6486aa3de5f4b45b :
missing '{' near line 13:1
	8:        	</head>
	9:        	<body>
	10:        		<h1>403 - Forbidden</h1>
	11:        	</body>
	12:        </html>
	13:     -> 

    at error (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:57:15)
    at declarations (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:214:25)
    at rule (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:481:21)
    at rules (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:103:56)
    at stylesheet (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:73:16)
    at Object.module.exports [as parse] (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:485:10)
    at process (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/src/uncss.js:158:22)
    at tryCatcher (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:452:31)
    at Promise._settlePromiseAt (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/chriswilliams/sites/yo-site/node_modules/grunt-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:415:13)
```

**Comment by XhmikosR** [comment]
It's an upstream issue, @giakki is aware of it, not sure when he will be able to have a look.
