### ISSUE TITLE
Uncss failing at source

### ISSUE THREAD

**Issue by ArcaneMainFrame** [addyosmani/grunt-uncss#74]
Not sure what I am doing wrong with my grunt configuration.  I do have this set locally and I have tried setting the htmlroot and stylesheets but it keeps giving this error with no idea as to why it fails:

> Running "uncss:dev" 
> verifying property 
> files: index.html -> css/site.css
> Options: compress=false, ignore=[""]
> Uncssing source "index.html' failed. 
> Warning: Uncss failed.  Use -force to continue

This is my gruntfile task: 

> uncss: {
>       dev: {
>         files: {
>           'css/site.css': ['index.html']
>         }
>       }
>     }

**Comment by seminice** [comment]
I'm having the same issue on mountain lion
node 0.12 , 0.11.14 , 0.10.36
I ran the grunt task in debugging mode , and here is the outcome

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1129:26)
    at Object.exports.spawn (child_process.js:988:9)
    at app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/lib/spawn.js:82:38
    at init (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/when.js:98:10)
    at startPhantom (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/lib/spawn.js:58:25)
    at tryCatchReject (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (app/node_modules/grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)


I tried placing the phantom binary in the same directory of the Gruntfile but it didn't work too.
Any help will be really appreciated, and great work anyway.

**Comment by seminice** [comment]
Solved it by editing the location.js file in  /grunt-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/location.js
I found out that the file is corrupted or something.

**Comment by jikuja** [comment]
@seminice :+1: Thanks your tip is nice. I just encountered same problem with global phantomjs installation. If you have idea how to reproduce that please tell or open new bug report in https://github.com/ariya/phantomjs/

**Comment by mikelambert** [comment]
This appears to be due to a half-completed installation of phantomjs-prebuilt, see this other issue for more info: https://github.com/Medium/phantomjs/issues/533

In my case, following these instructions fixed it for me:
```
$ cd node_modules/phantomjs-prebuilt
$ node install.js
```

**Comment by deanhume** [comment]
I followed @mikelambert instructions and this fixed the issue for me too. For some reason, the PhantomJS install never fully completed on MacOS and needed this nudge to complete it...saved me hours of frustration!
